examenes_app_principal/apps/front_examenes/urls.py
from django.urls import path

from .views import *

app_name = 'examenes'
urlpatterns = [
    path('preguntas/registrar', registrar_pregunta, name='registrar_pregunta'),
    path('preguntas/modificar/<int:pk>', modificar_pregunta, name='modificar_pregunta'),
    path('preguntas/listar', consultar_preguntas, name='consultar_preguntas'),
    path('preguntas/detalle/<int:pk>', detalle_pregunta, name='detalle_pregunta'),

    path('registrar', registrar_examen, name='registrar_examen'),
    path('modificar/<int:pk>', modificar_examen, name='modificar_examen'),
    path('listar', consultar_examenes, name='consultar_examenes'),
    path('detalle/<int:pk>', detalle_examen, name='detalle_examen'),

    path('iniciar-examen/<int:pk>', iniciar_examen, name='iniciar_examen'),
    path('terminar-examen/<int:pk>', terminar_examen, name='terminar_examen'),
    path('listar-calificaciones-examen/<int:pk>', consultar_calificaciones_examen, name='consultar_calificaciones_examen'),

    path('listar-examenes-estudiante', consultar_examenes_estudiante, name='consultar_examenes_estudiante'),
    path('listar-examenes-resueltos-estudiante', consultar_examenes_resueltos_estudiante, name='consultar_examenes_resueltos_estudiante'),

    path('responder-examen/<int:pk>', responder_examen, name='responder_examen'),
    path('ver-calificacion-examen/<int:pk>', ver_calificacion, name='ver_calificacion'),
]

examenes_app_principal/apps/front_grupos/urls.py
from django.urls import path

from .views import *

app_name = 'grupos'
urlpatterns = [
    path('registrar', registrar_grupo, name='registrar_grupo'),
    path('modificar/<int:pk>', modificar_grupo, name='modificar_grupo'),
    path('listar', consultar_grupos, name='consultar_grupos'),
    path('listar-grupos-estudiante', consultar_grupos_estudiante, name='consultar_grupos_estudiante'),
]

examenes_app_principal/apps/front_usuarios/urls.py
from django.urls import path

from .views import *

app_name = 'usuarios'
urlpatterns = [
    path('registrar', registrar_usuario, name='registrar_usuario'),
    path('modificar/<int:pk>', modificar_usuario, name='modificar_usuario'),
    path('listar', consultar_usuarios, name='consultar_usuarios'),
    path('detalle/<int:pk>', detalle_usuario, name='detalle_usuario'),
    path('login', Login.as_view(), name='login'),
    path('logout', Logout, name='logout'),
]

examenes_app_principal/examenes_app_principal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from apps.front_usuarios.views import inicio

urlpatterns = [
  path('usuarios/', include('apps.front_usuarios.urls')),
  path('grupos/', include('apps.front_grupos.urls')),
  path('examenes/', include('apps.front_examenes.urls')),

                path('', inicio, name='inicio'),
  path('select2/', include('django_select2.urls')),
  path('summernote/', include('django_summernote.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

examenes_app_principal/templates/menu/apps/examenes.html
<li class="has-sub">
    <a href="javascript:;">
        <b class="caret"></b>
        <i class="material-icons">assignment</i>
        <span>Examenes</span>
    </a>
    <ul class="sub-menu">
        <li><a href="{% url 'examenes:registrar_examen' %}">Registrar</a></li>
        <li><a href="{% url 'examenes:consultar_examenes' %}">Listar</a></li>
    </ul>
</li>

examenes_app_principal/templates/menu/apps/examenes_estudiante.html
<li class="has-sub">
    <a href="javascript:">
        <b class="caret"></b>
        <i class="material-icons">assignment</i>
        <span>Examenes</span>
    </a>
    <ul class="sub-menu">
        <li><a href="{% url 'examenes:consultar_examenes_estudiante' %}">Listar examenes pendientes</a></li>
        <li><a href="{% url 'examenes:consultar_examenes_resueltos_estudiante' %}">Listar examenes resueltos</a></li>
    </ul>
</li>

examenes_app_principal/templates/menu/apps/examenes_preguntas.html
<li class="has-sub">
    <a href="javascript:;">
        <b class="caret"></b>
        <i class="material-icons">question_answer</i>
        <span>Preguntas</span>
    </a>
    <ul class="sub-menu">
        <li><a href="{% url 'examenes:registrar_pregunta' %}">Registrar</a></li>
        <li><a href="{% url 'examenes:consultar_preguntas' %}">Listar</a></li>
    </ul>
</li>

examenes_app_principal/templates/menu/apps/grupos.html
<li class="has-sub">
    <a href="javascript:;">
        <b class="caret"></b>
        <i class="material-icons">people</i>
        <span>Grupos</span>
    </a>
    <ul class="sub-menu">
        {% if user.rol == 'Profesor' %}
            <li><a href="{% url 'grupos:registrar_grupo' %}">Registrar</a></li>
            <li><a href="{% url 'grupos:consultar_grupos' %}">Listar</a></li>
        {% elif user.rol == 'Estudiante' %}
            <li><a href="{% url 'grupos:consultar_grupos_estudiante' %}">Listar</a></li>
        {% endif %}
    </ul>
</li>

examenes_app_principal/templates/menu/apps/usuarios.html
<li class="has-sub">
    <a href="javascript:;">
        <b class="caret"></b>
        <i class="material-icons">book</i>
        <span>Usuarios</span>
    </a>
    <ul class="sub-menu">
        <li><a href="{% url 'usuarios:registrar_usuario' %}">Registrar</a></li>
        <li><a href="{% url 'usuarios:consultar_usuarios' %}">Listar</a></li>
    </ul>
</li>