examenes_app_principal/apps/front_usuarios/urls.py
from django.urls import path

from .views import *

app_name = 'usuarios'
urlpatterns = [
    path('registrar', registrar_usuario, name='registrar_usuario'),
    path('modificar/<int:pk>', modificar_usuario, name='modificar_usuario'),
    path('listar', consultar_usuarios, name='consultar_usuarios'),
    path('detalle/<int:pk>', detalle_usuario, name='detalle_usuario'),
    path('login', Login.as_view(), name='login'),
    path('logout', Logout, name='logout'),
]

examenes_app_principal/examenes_app_principal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from apps.front_usuarios.views import inicio

urlpatterns = [
  path('usuarios/', include('apps.front_usuarios.urls')),
  path('grupos/', include('apps.front_grupos.urls')),
  path('examenes/', include('apps.front_examenes.urls')),

                path('', inicio, name='inicio'),
  path('select2/', include('django_select2.urls')),
  path('summernote/', include('django_summernote.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

examenes_app_principal/apps/front_usuarios/forms.py
from django import forms
from django.contrib.auth import password_validation


class RegistrarUsuarioForm(forms.Form):
    ROLES = (
        ("Administrador", "Administrador"),
        ("Profesor", "Profesor"),
        ("Estudiante", "Estudiante"),
    )

    error_messages = {
        'password_mismatch': "Las contraseñas no coinciden",
    }

    first_name = forms.CharField(max_length=150, label="Nombres")
    last_name = forms.CharField(max_length=150, label="Apellidos")
    username = forms.CharField(max_length=150, label="Nombre de usuario")
    email = forms.CharField(max_length=150, label="Correo electrónico")
    rol = forms.ChoiceField(choices=ROLES)
    imagen_perfil = forms.ImageField(required=False)

    password = forms.CharField(
            label="Contraseña",
            strip=False,
            widget=forms.PasswordInput,
            help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
            label="Confirmar contraseña",
            widget=forms.PasswordInput,
            strip=False,
            help_text="Ingrese de nuevo la misma contraseña",
    )

    def clean_password2(self):
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password and password2 and password != password2:
            raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
            )
        return password2


class ModificarUsuarioForm(forms.Form):
    ROLES = (
        ("Administrador", "Administrador"),
        ("Profesor", "Profesor"),
        ("Estudiante", "Estudiante"),
    )

    first_name = forms.CharField(max_length=150, label="Nombres")
    last_name = forms.CharField(max_length=150, label="Apellidos")
    username = forms.CharField(max_length=150, label="Nombre de usuario")
    email = forms.CharField(max_length=150, label="Correo electrónico")
    rol = forms.ChoiceField(choices=ROLES)
    imagen_perfil = forms.ImageField(required=False)


class LoginForm(forms.Form):
    username = forms.CharField(max_length=50, label='Nombre de usuario',
                               widget=forms.TextInput(attrs={
                                   'class': 'form-control',
                                   'placeholder': '',
                               }))

    password = forms.CharField(max_length=50, label='Contraseña',
                               widget=forms.TextInput(attrs={
                                   'type': 'password',
                                   'class': 'form-control',
                                   'placeholder': '',
                               }))

examenes_app_principal/apps/front_usuarios/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import FormView
from django_microservices.models import MicroService
from django_microservices.utilities import authenticate, login, logout, login_required
from rest_framework import status

from examenes_app_principal.utilities import verificar_rol
from .forms import *


@login_required
@verificar_rol(roles_permitidos=["Administrador"])
def registrar_usuario(request):
    form = RegistrarUsuarioForm()

    microservicio = MicroService.objects.get(name="api")

    if request.method == 'POST':
        try:
            respuesta = microservicio.remote_call(
                    "POST", api='api/usuarios/', data=request.POST, files=request.FILES, request=request
            )
        except Exception:
            messages.error(request, 'Ha ocurrido un error al guardar la información, por favor vuelva a intentar.')
            return redirect('usuarios:consultar_usuarios')

        form = RegistrarUsuarioForm(request.POST, request.FILES)
        if respuesta.status_code == status.HTTP_201_CREATED:
            return redirect('usuarios:consultar_usuarios')
        elif respuesta.status_code == status.HTTP_400_BAD_REQUEST:
            errores = respuesta.json()
            form = RegistrarUsuarioForm(request.POST, request.FILES)
            for campo, error in errores.items():
                form.add_error(campo, error)

            return render(request, "registrar_usuario.html", {'form': form})

    return render(request, "registrar_usuario.html", {'form': form})


@login_required
@verificar_rol(roles_permitidos=["Administrador"])
def modificar_usuario(request, pk):
    microservicio = MicroService.objects.get(name="api")
    try:
        respuesta = microservicio.remote_call(
                "GET", api='api/usuarios/%s' % pk, request=request
        )
    except Exception:
        messages.error(request, 'Ha ocurrido un error, por favor vuelva a intentar.')
        return redirect('inicio')

    if respuesta.status_code == 200:
        usuario = respuesta.json()
    else:
        messages.error(request, 'Error al obtener los datos del usuario')
        return redirect('usuarios:consultar_usuarios')

    form = ModificarUsuarioForm(initial=usuario)

    if request.method == 'POST':
        try:
            respuesta = microservicio.remote_call(
                    "POST", api='api/usuarios/%s' % usuario['id'], data=request.POST, files=request.FILES, request=request
            )
        except Exception:
            messages.error(request, 'Ha ocurrido un error al guardar la información, por favor vuelva a intentar.')
            return redirect('inicio')

        form = ModificarUsuarioForm(request.POST, request.FILES, initial=usuario)
        if respuesta.status_code == status.HTTP_200_OK:
            return redirect('usuarios:consultar_usuarios')
        elif respuesta.status_code == status.HTTP_400_BAD_REQUEST:
            errores = respuesta.json()
            for campo, error in errores.items():
                form.add_error(campo, error)

            return render(request, "modificar_usuario.html", {'form': form})
        else:
            messages.error(request, 'Ha ocurrido un error al guardar la información, por favor vuelva a intentar.')
            return redirect('usuarios:consultar_usuarios')

    return render(request, "modificar_usuario.html", {'form': form})


@login_required
def consultar_usuarios(request):
    microservicio = MicroService.objects.get(name="api")
    try:
        respuesta = microservicio.remote_call(
                "GET", api='api/usuarios/', request=request
        )
    except Exception:
        messages.error(request, 'Ha ocurrido un error, por favor vuelva a intentar.')
        return redirect('inicio')

    if respuesta.status_code == 200:
        usuarios = respuesta.json()
    else:
        return HttpResponse(respuesta.status_code)

    return render(request, "lista_usuarios.html", {'lista_usuarios': usuarios})


@login_required
def detalle_usuario(request, pk):
    microservicio = MicroService.objects.get(name="api")
    try:
        respuesta = microservicio.remote_call(
                "GET", api='api/usuarios/%s' % pk, request=request
        )
    except Exception:
        messages.error(request, 'Ha ocurrido un error, por favor vuelva a intentar.')
        return redirect('usuarios:consultar_usuarios')

    if respuesta.status_code == 200:
        usuario = respuesta.json()
    else:
        messages.error(request, "Ha ocurrido un error, por favor vuelva a intentar.")
        return redirect('usuarios:consultar_usuarios')

    return render(request, "detalle_usuario.html", {'usuario': usuario})


@login_required
def inicio(request):
    return render(request, 'base.html')


class Login(FormView):
    form_class = LoginForm
    template_name = 'login.html'
    success_url = reverse_lazy('inicio')

    def form_valid(self, form):
        try:
            usuario = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        except Exception:
            messages.error(self.request, "Ha ocurrido un error, por favor vuelva a intentarlo")
            return super(Login, self).form_invalid(form)

        if usuario is not None:
            # if usuario.is_active:
            login(self.request, usuario)
            redireccion = self.request.session.pop('_next_login', None)
            if redireccion:
                return redirect(redireccion)
            return super(Login, self).form_valid(form)
        # elif not usuario.is_active:
        #     mensaje = _("El usuario %s no esta activo" % (usuario.username))
        else:
            mensaje = "El usuario no existe o la contraseña es incorrecta"
        form.add_error('username', mensaje)
        messages.add_message(self.request, messages.ERROR, mensaje)
        return super(Login, self).form_invalid(form)

    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR, "Ingrese un usuario y una contraseña para acceder al sistema")
        return super(Login, self).form_invalid(form)


def Logout(request):
    logout(request)
    messages.success(request, "Sesión cerrada correctamente")
    return redirect('inicio')

examenes_app_principal/apps/front_usuarios/templates/detalle_usuario.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block titulo_pagina %}
    Información de usuario
{% endblock %}

{% block titulo %}
    Información de usuario
{% endblock %}

{% block subtitulo %}
    Información detallada del usuario
{% endblock %}

{% block titulo_panel %}
    Información de {{ usuario.first_name }} {{ usuario.last_name }}
{% endblock %}

{% block contenido_panel %}
    <div class="row d-flex" style="justify-content: center">
        <div class="col-md-8">
            <div class="row">
                <div class="col-sm-12 col-md-6 col-lg-3">
                    <img class="img-usuario" src="{% if usuario.imagen_perfil %}{{ usuario.imagen_perfil }}{% else %}{% static 'img/user/user-12.jpg' %}{% endif %}">
                </div>
                <div class="col-sm-12 col-md-6 col-lg-9">
                    <p>
                        <b>Nombre: </b>{{ usuario.first_name }} {{ usuario.last_name }}
                    </p>
                    <p>
                        <b>Correo electrónico: </b> {{ usuario.email }}
                    </p>
                    <p>
                        <b>Nombre de usuario: </b> {{ usuario.username }}
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 m-t-10">
                    <a class="btn btn-default pull-left" href="{% if request.META.HTTP_REFERER %}{{ request.META.HTTP_REFERER }}{% else %}{% url 'inicio' %}{% endif %}">Volver</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

examenes_app_principal/apps/front_usuarios/templates/lista_usuarios.html
{% extends "base_tablas.html" %}

{% block titulo_pagina %}
    Listado de usuarios
{% endblock %}

{% block titulo %}
    Listado de usuarios
{% endblock %}

{% block subtitulo %}
    Información de los usuarios del sistema
{% endblock %}

{% block titulo_panel %}
    Listado de  usuarios
{% endblock %}

{% block contenido_panel %}
    <table class="data-combine table table-bordered">
        <thead>
            <tr>
                <th>
                    Nombre
                </th>
                <th>
                    Nombre de usuario
                </th>
                <th>
                    Email
                </th>
                <th>
                    Rol
                </th>
                <th>
                    Opciones
                </th>
            </tr>
        </thead>
        <tbody>
            {% for usuario in lista_usuarios %}
                <tr>
                    <td>
                        {{ usuario.first_name }} {{ usuario.last_name }}
                    </td>
                    <td>
                        {{ usuario.username }}
                    </td>
                    <td>
                        {{ usuario.email }}
                    </td>
                    <td>
                        {{ usuario.rol }}
                    </td>
                    <td>
                        <a class="btn btn-sm btn-info" href="{% url 'usuarios:detalle_usuario' usuario.id %}">Ver datos</a>
                        <a class="btn btn-sm btn-info" href="{% url 'usuarios:modificar_usuario' usuario.id %}">Modificar</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

examenes_app_principal/apps/front_usuarios/templates/login.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<!--[if IE 8]> <html lang="es" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="es">
<!--<![endif]-->
<head>
    <meta charset="utf-8"/>
    <title>ExamSys | Iniciar sesión</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>
    <meta content="" name="description"/>
    <meta content="" name="author"/>

    <!-- ================== BEGIN BASE CSS STYLE ================== -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100italic,300,300italic,400,400italic,500,500italic,700,700italic,900,900italic" rel="stylesheet" type="text/css' %}"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons' %}" rel="stylesheet"/>
    <link href="{% static 'plugins/jquery-ui/jquery-ui.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'plugins/bootstrap/4.1.0/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'plugins/font-awesome/5.0/css/fontawesome-all.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'plugins/animate/animate.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/style-responsive.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/theme/default.css' %}" rel="stylesheet" id="theme"/>
    <!-- ================== END BASE CSS STYLE ================== -->
    <link href="{% static 'plugins/toastr/toastr.min.css' %}" rel="stylesheet"/>

    <!-- ================== BEGIN BASE JS ================== -->
    <script src="{% static 'plugins/pace/pace.min.js' %}"></script>
    <!-- ================== END BASE JS ================== -->
</head>
<body class="pace-top">
<!-- begin #page-loader -->
<div id="page-loader" class="fade show">
    <div class="material-loader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10"></circle>
        </svg>
        <div class="message">Loading...</div>
    </div>
</div>
<!-- end #page-loader -->

<!-- begin #page-container -->
<div id="page-container" class="fade">
    <!-- begin login -->
    <div class="login bg-black animated fadeInDown">
        <!-- begin brand -->
        <div class="login-header">
            <div class="brand">
                ExamSys
                <small>Iniciar sesión</small>
            </div>
            <div class="icon">
                <i class="fa fa-lock"></i>
            </div>
        </div>
        <!-- end brand -->
        <!-- begin login-content -->
        <div class="login-content">
            <form method="POST" class="margin-bottom-0">{% csrf_token %}
                {% bootstrap_form form %}
                <div class="login-buttons">
                    <button type="submit" class="btn btn-success btn-block btn-lg">Iniciar sesión</button>
                </div>
            </form>
        </div>
        <!-- end login-content -->
    </div>
    <!-- end login -->

</div>
<!-- end page container -->

<!-- ================== BEGIN BASE JS ================== -->
<script src="{% static 'plugins/jquery/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/4.1.0/js/bootstrap.bundle.min.js' %}"></script>
<!--[if lt IE 9]>
		<script src="{% static 'crossbrowserjs/html5shiv.js' %}" ></script>
		<script src="{% static 'crossbrowserjs/respond.min.js' %}" ></script>
		<script src="{% static 'crossbrowserjs/excanvas.min.js' %}" ></script>
	<![endif]-->
<script src="{% static 'plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'plugins/js-cookie/js.cookie.js' %}"></script>
<script src="{% static 'js/theme/material.min.js' %}"></script>
<script src="{% static 'js/apps.min.js' %}"></script>
<!-- ================== END BASE JS ================== -->
<script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>

<script>
    $(document).ready(function () {
        App.init();
    });

    toastr.options = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": true,
        "progressBar": true,
        "positionClass": "toast-top-right",
        "preventDuplicates": true,
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "15000",
        "extendedTimeOut": "50000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    };


    {% for msg in messages %}
        $(document).ready(function () {
            setTimeout(function () {
                toastr["{{ msg.tags }}"]("{{msg}}")
            }, 500);
        });
    {% endfor %}
</script>
</body>
</html>

examenes_app_principal/apps/front_usuarios/templates/modificar_usuario.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block titulo_panel %}
    Registrar usuario
{% endblock %}

{% block contenido_panel %}
    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
        {% bootstrap_form form layout="vertical" %}
        <button type="submit" class="btn btn-default">Enviar</button>
    </form>
{% endblock %}

examenes_app_principal/apps/front_usuarios/templates/registrar_usuario.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block titulo_panel %}
    Registrar usuario
{% endblock %}

{% block contenido_panel %}
    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
        {% bootstrap_form form layout="vertical" %}
        <button type="submit" class="btn btn-default">Enviar</button>
    </form>
{% endblock %}