examenes_app_principal/apps/front_examenes/urls.py
from django.urls import path

from .views import *

app_name = 'examenes'
urlpatterns = [
    path('preguntas/registrar', registrar_pregunta, name='registrar_pregunta'),
    path('preguntas/modificar/<int:pk>', modificar_pregunta, name='modificar_pregunta'),
    path('preguntas/listar', consultar_preguntas, name='consultar_preguntas'),
    path('preguntas/detalle/<int:pk>', detalle_pregunta, name='detalle_pregunta'),

    path('registrar', registrar_examen, name='registrar_examen'),
    path('modificar/<int:pk>', modificar_examen, name='modificar_examen'),
    path('listar', consultar_examenes, name='consultar_examenes'),
    path('detalle/<int:pk>', detalle_examen, name='detalle_examen'),

    path('iniciar-examen/<int:pk>', iniciar_examen, name='iniciar_examen'),
    path('terminar-examen/<int:pk>', terminar_examen, name='terminar_examen'),
    path('listar-calificaciones-examen/<int:pk>', consultar_calificaciones_examen, name='consultar_calificaciones_examen'),

    path('listar-examenes-estudiante', consultar_examenes_estudiante, name='consultar_examenes_estudiante'),
    path('listar-examenes-resueltos-estudiante', consultar_examenes_resueltos_estudiante, name='consultar_examenes_resueltos_estudiante'),

    path('responder-examen/<int:pk>', responder_examen, name='responder_examen'),
    path('ver-calificacion-examen/<int:pk>', ver_calificacion, name='ver_calificacion'),
]

examenes_app_principal/examenes_app_principal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from apps.front_usuarios.views import inicio

urlpatterns = [
  path('usuarios/', include('apps.front_usuarios.urls')),
  path('grupos/', include('apps.front_grupos.urls')),
  path('examenes/', include('apps.front_examenes.urls')),

                path('', inicio, name='inicio'),
  path('select2/', include('django_select2.urls')),
  path('summernote/', include('django_summernote.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

examenes_app_principal/apps/front_examenes/models.py
# Create your models here.

examenes_app_principal/apps/front_examenes/forms.py
from django import forms
from django.forms.formsets import BaseFormSet
from django_microservices.models import MicroService
from django_summernote.widgets import SummernoteWidget


class PreguntaForm(forms.Form):
    enunciado = forms.CharField(widget=SummernoteWidget(attrs={
        'data-parsley-group': 'step-1',
        'data-parsley-required': 'true'
    }))


class RespuestaForm(forms.Form):
    id = forms.IntegerField(required=False)
    respuesta = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 4,
        'style': 'resize:none;',
        'data-parsley-group': 'step-2',
        'data-parsley-required': 'true'
    }))
    imagen = forms.ImageField(required=False)
    es_correcta = forms.BooleanField(required=False)


class ExamenForm(forms.Form):
    titulo = forms.CharField(max_length=255, label='Título')
    grupo = forms.ChoiceField(label="Grupo")
    fecha_inicio = forms.DateTimeField(label="Fecha de inicio")
    fecha_fin = forms.DateTimeField(label="Fecha de finalización")
    preguntas_originales = forms.MultipleChoiceField(label="Preguntas", required=False, widget=forms.CheckboxSelectMultiple())

    def __init__(self, *args, **kwargs):
        profesor = kwargs.pop('profesor', None)
        examen = kwargs.pop('examen', None)
        super(ExamenForm, self).__init__(*args, **kwargs)
        try:
            microservicio = MicroService.objects.get(name="api")
            respuesta = microservicio.remote_call(
                    "GET", api='api/grupos/', headers={'MICROSERVICE-USER-PK': str(profesor['id'])}
            )

            if respuesta.status_code == 200:
                grupos = []
                for grupo in respuesta.json():
                    grupos.append((grupo['id'], grupo['nombre']))
            else:
                grupos = []
        except Exception:
            grupos = []

        self.fields['grupo'].choices = grupos

        try:
            microservicio = MicroService.objects.get(name="api")
            respuesta = microservicio.remote_call(
                    "GET", api='api/examenes/preguntas', headers={'MICROSERVICE-USER-PK': str(profesor['id'])}
            )
            if respuesta.status_code == 200:
                preguntas_originales = []
                for pregunta in respuesta.json():
                    preguntas_originales.append((pregunta['id'], pregunta['enunciado']))
            else:
                preguntas_originales = []
        except Exception as e:
            preguntas_originales = []
        self.fields['preguntas_originales'].choices = preguntas_originales

        if examen:
            self.initial['preguntas_originales'] = [pregunta['id'] for pregunta in examen['preguntas_originales']]


class PreguntaResueltaForm(forms.Form):
    respuestas_seleccionadas = forms.MultipleChoiceField(label="Respuestas", required=False, widget=forms.CheckboxSelectMultiple)
    id = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        self.pregunta = kwargs.pop('pregunta', None)
        self.lista_preguntas = kwargs.pop('lista_preguntas', None)

        super(PreguntaResueltaForm, self).__init__(*args, **kwargs)

        self.fields['respuestas_seleccionadas'].choices = [(respuesta['id'], respuesta['respuesta']) for respuesta in self.pregunta.get('respuestas')]

        self.initial['respuestas_seleccionadas'] = [respuesta['id'] for respuesta in self.pregunta.get('respuestas_seleccionadas')]
        self.fields['id'].initial = self.pregunta['id']

class BasePreguntasFormSet(BaseFormSet):
    def get_form_kwargs(self, index):
        kwargs = super(BasePreguntasFormSet, self).get_form_kwargs(index)
        kwargs['pregunta'] = kwargs['lista_preguntas'][index]
        return kwargs

examenes_app_principal/apps/front_examenes/views.py
from django.conf import settings
from django.contrib import messages
from django.forms import formset_factory
from django.http import JsonResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect
from django_microservices.utilities import get_microservice_user_pk, get_microservice_user
from django_microservices.utilities import login_required
from rest_framework import status

from examenes_app_principal.utilities import verificar_rol, add_form_errors
from .forms import *


@login_required
@verificar_rol(roles_permitidos=["Profesor"])
def registrar_pregunta(request):
    form = PreguntaForm()
    numero_respuestas = 4
    RespuestaFormSet = formset_factory(form=RespuestaForm, extra=numero_respuestas, max_num=numero_respuestas)
    formset_respuestas = RespuestaFormSet()

    microservicio = MicroService.objects.get(name="api")

    if request.method == 'POST':
        form = PreguntaForm(request.POST, request.FILES)
        formset_respuestas = RespuestaFormSet(request.POST, request.FILES)
        try:
            if form.is_valid() and formset_respuestas.is_valid():
                data = form.cleaned_data
                data['creador'] = get_microservice_user_pk(request)
                respuestas = []
                for form_respuesta in formset_respuestas.forms:
                    respuestas.append(form_respuesta.cleaned_data)

                data['respuestas'] = respuestas

                respuesta = microservicio.remote_call(
                        "POST", api='api/examenes/preguntas', json=data, files=request.FILES, request=request
                )
            else:
                messages.error(request, "Por favor revise los campos en rojo")
                return render(request, "registrar_pregunta.html", {'form': form, 'formset_respuestas': formset_respuestas})

        except Exception as e:
            messages.error(request, 'Ha ocurrido un error al guardar la información, por favor vuelva a intentar.')
            return render(request, "registrar_pregunta.html", {'form': form, 'formset_respuestas': formset_respuestas})

        form = PreguntaForm(request.POST, request.FILES)
        formset_respuestas = RespuestaFormSet(request.POST, request.FILES)
        if respuesta.status_code == status.HTTP_201_CREATED:
            messages.success(request, "Pregunta registrada correctamente")
            return redirect('examenes:consultar_preguntas')
        elif respuesta.status_code == status.HTTP_400_BAD_REQUEST:
            errores = respuesta.json()
            form = PreguntaForm(request.POST, request.FILES)
            formset_respuestas = RespuestaFormSet(request.POST, request.FILES)

            add_form_errors(form, errores)
            messages.error(request, "Por favor revise los campos en rojo")
            return render(request, "registrar_pregunta.html", {'form': form, 'formset_respuestas': formset_respuestas})

    return render(request, "registrar_pregunta.html", {'form': form, 'formset_respuestas': formset_respuestas})


@login_required
@verificar_rol(roles_permitidos=["Profesor"])
def modificar_pregunta(request, pk):
    microservicio = MicroService.objects.get(name="api")
    try:
        respuesta = microservicio.remote_call(
                "GET", api='api/examenes/preguntas/%s' % pk, request=request
        )
    except Exception:
        messages.error(request, 'Ha ocurrido un error, por favor vuelva a intentar.')
        return redirect('inicio')

    if respuesta.status_code == 200:
        pregunta = respuesta.json()
    else:
        messages.error(request, 'Error al obtener los datos de la pregunta')
        return redirect('examenes:consultar_preguntas')
    form = PreguntaForm(initial=pregunta)
    resuestas_iniciales = [respuesta for respuesta in pregunta.get('respuestas')]
    numero_respuestas = len(resuestas_iniciales)
    RespuestaFormSet = formset_factory(form=RespuestaForm, extra=numero_respuestas, max_num=numero_respuestas)
    formset_respuestas = RespuestaFormSet(initial=resuestas_iniciales)

    if request.method == 'POST':
        form = PreguntaForm(request.POST, request.FILES, initial=pregunta)
        formset_respuestas = RespuestaFormSet(request.POST, request.FILES, initial=resuestas_iniciales)
        if form.is_valid() and formset_respuestas.is_valid():
            data = form.cleaned_data
            data['creador'] = pregunta['creador']
            data['respuestas'] = formset_respuestas.cleaned_data
        else:
            messages.error(request, "Por favor revise los campos en rojo")
            return render(request, "modificar_pregunta.html", {'form': form, 'formset_respuestas': formset_respuestas})

        try:
            respuesta = microservicio.remote_call(
                    "POST", api='api/examenes/preguntas/%s' % pk, json=data, files=request.FILES, request=request
            )
            if respuesta.status_code == status.HTTP_200_OK:
                messages.success(request, "Pregunta registrada correctamente")
                return redirect('examenes:consultar_preguntas')
            elif respuesta.status_code == status.HTTP_400_BAD_REQUEST:
                errores = respuesta.json()
                add_form_errors(form, errores)
                messages.error(request, "Por favor revise los campos en rojo")
                return render(request, "modificar_pregunta.html", {'form': form, 'formset_respuestas': formset_respuestas})
            else:
                messages.error(request, 'Ha ocurrido un error al guardar la información, por favor vuelva a intentar.')
                return render(request, "modificar_pregunta.html", {'form': form, 'formset_respuestas': formset_respuestas})
        except Exception as e:
            messages.error(request, 'Ha ocurrido un error al guardar la información, por favor vuelva a intentar.')
            return render(request, "modificar_pregunta.html", {'form': form, 'formset_respuestas': formset_respuestas})

    return render(request, "modificar_pregunta.html", {'form': form, 'formset_respuestas': formset_respuestas})


@login_required
def consultar_preguntas(request):
    microservicio = MicroService.objects.get(name="api")
    try:
        respuesta = microservicio.remote_call(
                "GET", api='api/examenes/preguntas', request=request
        )
    except Exception as e:
        messages.error(request, 'Ha ocurrido un error, por favor vuelva a intentar.')
        return redirect('inicio')

    if respuesta.status_code == 200:
        preguntas = respuesta.json()
    else:
        messages.error(request, 'Ha ocurrido un error, por favor vuelva a intentar.')
        return redirect('inicio')

    return render(request, "lista_preguntas.html", {'lista_preguntas': preguntas})


@login_required
def detalle_pregunta(request, pk):
    microservicio = MicroService.objects.get(name="api")
    try:
        respuesta = microservicio.remote_call(
                "GET", api='api/examenes/preguntas/%s' % pk, request=request
        )
    except Exception:
        messages.error(request, 'Ha ocurrido un error, por favor vuelva a intentar.')
        return redirect('examenes:consultar_preguntas')

    if respuesta.status_code == 200:
        pregunta = respuesta.json()
    else:
        messages.error(request, "Ha ocurrido un error, por favor vuelva a intentar.")
        return redirect('examenes:consultar_preguntas')

    return render(request, "detalle_pregunta.html", {'pregunta': pregunta})


@login_required
@verificar_rol(roles_permitidos=["Profesor"])
def registrar_examen(request):
    profesor = get_microservice_user(request)
    form = ExamenForm(profesor=profesor)
    microservicio = MicroService.objects.get(name="api")

    if request.method == 'POST':
        form = ExamenForm(request.POST, profesor=profesor)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            data = {}
            data['titulo'] = cleaned_data['titulo']
            data['profesor'] = profesor[settings.MICROSERVICE_USER_PK_KEY]
            data['grupo'] = cleaned_data['grupo']
            data['fecha_inicio'] = cleaned_data['fecha_inicio'].strftime("%Y-%m-%d %H:%M:%S")
            data['fecha_fin'] = cleaned_data['fecha_fin'].strftime("%Y-%m-%d %H:%M:%S")
            data['preguntas_originales'] = cleaned_data['preguntas_originales']
        else:
            messages.error(request, "Por favor revise los campos en rojo")
            return render(request, "gestionar_examen.html", {'form': form})

        try:
            respuesta = microservicio.remote_call(
                    "POST", api='api/examenes/', json=data, request=request
            )
        except Exception as e:
            messages.error(request, 'Ha ocurrido un error al guardar la información, por favor vuelva a intentar.')
            return redirect('examenes:consultar_examenes')

        if respuesta.status_code == status.HTTP_201_CREATED:
            messages.success(request, "Examen registrado correctamente")
            return redirect('examenes:consultar_examenes')
        elif respuesta.status_code == status.HTTP_400_BAD_REQUEST:
            errores = respuesta.json()
            add_form_errors(form, errores)
            messages.error(request, "Por favor revise los campos en rojo")
            return render(request, "gestionar_examen.html", {'form': form})
        else:
            messages.error(request, 'Ha ocurrido un error al guardar la información, por favor vuelva a intentar.')
            return redirect('examenes:consultar_examenes')

    return render(request, "gestionar_examen.html", {'form': form})


@login_required
@verificar_rol(roles_permitidos=["Profesor"])
def modificar_examen(request, pk):
    profesor = get_microservice_user(request)
    microservicio = MicroService.objects.get(name="api")

    try:
        respuesta = microservicio.remote_call(
                "GET", api='api/examenes/%s' % pk, request=request
        )
    except Exception:

examenes_app_principal/apps/front_examenes/templates/_informacion_pregunta.html
<div class="row">
    <div class="col-sm-12">
        <div class="row">
            <h4>Enunciado:</h4>
            <div class="col-sm-12">
                <div class="card card-outline-default">
                    <div class="card-block">
                        <div class="enunciado-pregunta table-responsive">
                            {{ pregunta.enunciado|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <h5>Opciones de respuesta:</h5>
            {% for respuesta in pregunta.respuestas %}
                <div class="col-sm-12">
                    <div class="card {% if respuesta.es_correcta %}card-outline-success{% else %}card-outline-info{% endif %}">
                        {% if respuesta.es_correcta %}
                            <div class="card-block">
                                <h4 style="color: green">Respuesta correcta</h4>
                            </div>
                        {% endif %}
                        <div class="card-block d-flex flex-row justify-content-start flex-wrap-reverse align-items-center">
                            {% if respuesta.imagen %}
                                <img class="img-pregunta m-10" src="{{ respuesta.imagen.url }}">
                            {% endif %}
                            <p class="m-10">
                                {{ respuesta.respuesta }}
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
<script>

</script>

examenes_app_principal/apps/front_examenes/templates/gestionar_examen.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block titulo_pagina %}
    Gestión de examen
{% endblock %}

{% block titulo %}
    Gestión de examen
{% endblock %}

{% block subtitulo %}
    Creación y edición de examenes
{% endblock %}

{% block titulo_panel %}
    Gestión de examen
{% endblock %}

{% block css %}
    <link href="{% static 'plugins/DataTables/media/css/dataTables.bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'plugins/DataTables/extensions/Buttons/css/buttons.bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'plugins/DataTables/extensions/ColReorder/css/colReorder.bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'plugins/bootstrap-eonasdan-datetimepicker/build/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'plugins/jquery-smart-wizard/src/css/smart_wizard.css' %}" rel="stylesheet"/>
    <link href="{% static 'plugins/parsley/src/parsley.css' %}" rel="stylesheet"/>
    <style>
        tr.pregunta-seleccionada > td:first-child {
            border-left: 1px solid rgba(76, 175, 80, .9) !important;
            border-top: 1px solid rgba(76, 175, 80, .9) !important;
            border-bottom: 1px solid rgba(76, 175, 80, .9) !important;
        }

        tr.pregunta-seleccionada > td:last-child {
            border-right: 1px solid rgba(76, 175, 80, .9) !important;
            border-top: 1px solid rgba(76, 175, 80, .9) !important;
            border-bottom: 1px solid rgba(76, 175, 80, .9) !important;
        }

        tr.pregunta-seleccionada > td {
            border-top: 1px solid rgba(76, 175, 80, .9) !important;
            border-bottom: 1px solid rgba(76, 175, 80, .9) !important;
        }

        tr.pregunta-seleccionada {
            background: rgba(76, 175, 80, .3) !important;
        }
    </style>
{% endblock %}

{% block contenido_panel %}
    <div class="row d-flex justify-content-center">
        <div class="col-md-12">
            <form method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div class="row">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-sm-12 col-md-6">
                                {% bootstrap_field form.titulo layout="vertical" %}
                                {% bootstrap_field form.grupo layout="vertical" %}
                            </div>
                            <div class="col-sm-12 col-md-6">
                                {% bootstrap_field form.fecha_inicio layout="vertical" %}
                                {% bootstrap_field form.fecha_fin layout="vertical" %}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">

                        {% if form.preguntas_originales.errors %}
                            <div class="alert alert-danger fade show">
                                <span class="close" data-dismiss="alert">×</span>
                                <b>Preguntas seleccionadas</b>
                                {{ form.preguntas_originales.errors }}
                            </div>
                        {% else %}
                            <b>Preguntas seleccionadas</b>
                        {% endif %}
                        <div class="table-responsive">
                            <table id="data-combine" class="data-combine table table-bordered">
                                <thead>
                                    <tr>
                                        <th style="width: 15%">
                                            Seleccionar
                                        </th>
                                        <th>
                                            Enunciado
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for pregunta in form.preguntas_originales %}
                                        <tr>
                                            <td style="text-align: center">
                                                <div style="display:none">
                                                    {{ pregunta }}
                                                </div>
                                                <p class="texto-seleccionada"></p>
                                            </td>
                                            <td>
                                                <div class="enunciado-pregunta table-responsive">
                                                    {{ pregunta.data.label|safe }}
                                                </div>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
{#                <a class="btn btn-default pull-left" href="{% url 'examenes:consultar_examenes' %}">Volver</a>#}
                <button type="submit" class="btn btn-primary pull-right">Enviar</button>
            </form>
        </div>


    </div>
{% endblock %}

{% block js %}

    <script src="{% static 'plugins/DataTables/media/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'plugins/DataTables/media/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/DataTables/extensions/Buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'plugins/DataTables/extensions/Buttons/js/buttons.bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/DataTables/extensions/Buttons/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'plugins/DataTables/extensions/Buttons/js/jszip.min.js' %}"></script>
    <script src="{% static 'plugins/DataTables/extensions/Buttons/js/pdfmake.min.js' %}"></script>
    <script src="{% static 'plugins/DataTables/extensions/Buttons/js/vfs_fonts.min.js' %}"></script>
    <script src="{% static 'plugins/DataTables/extensions/Buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'plugins/DataTables/extensions/Buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'plugins/DataTables/extensions/ColReorder/js/dataTables.colReorder.min.js' %}"></script>
    <script>
        var static_url = "{% get_static_prefix %}";
    </script>
    <script src="{% static 'plugins/bootstrap-daterangepicker/moment.js' %}"></script>

    <script src="{% static 'plugins/bootstrap-eonasdan-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}"></script>

    <script>
        $fecha_inicio = $('#id_fecha_inicio');
        $fecha_fin = $('#id_fecha_fin');
        console.log($fecha_inicio.val());
        $fecha_inicio.datetimepicker({
            'format': 'YYYY-MM-DD HH:mm'
        });

        $fecha_fin.datetimepicker({
            'format': 'YYYY-MM-DD HH:mm',
        });
        $fecha_inicio.on("dp.change", function (e) {
            $('#id_fecha_fin').data("DateTimePicker").minDate(e.date);
        });
        $fecha_fin.on("dp.change", function (e) {
            $('#id_fecha_inicio').data("DateTimePicker").maxDate(e.date);
        });
    </script>
    <script>

        $(document).ready(function () {
            var table = $('#data-combine').DataTable({
                dom: 'lBfrtip',
                buttons: [],
                rowReorder: true,
                "language": {
                    "url": static_url + "plugins/DataTables/media/i18n/Spanish.json"
                },
                order: [0],
                columnDefs: [
                    {
                        targets: [0],
                        render: function (data, type, full, meta) {
                            if (type === 'sort') {
                                var api = new $.fn.dataTable.Api(meta.settings);
                                var td = api.cell({row: meta.row, column: meta.col}).node();
                                var $input = $('select, input', td);
                                if ($input.length && $input.is(':checked')) {
                                    data = 1;
                                } else {
                                    data = 0;
                                }
                            }
                            return data;
                        }
                    }
                ]
            });

            $('tbody input', table.table().node()).on('change', function (e) {
                table.row($(this).closest('tr')).invalidate();
                if ($(this).prop('checked')) {
                    $(this).closest('tr').addClass('pregunta-seleccionada')
                } else {
                    $(this).closest('tr').removeClass('pregunta-seleccionada')
                }
            });

            $('tbody tr', table.table().node()).on('click', function (e) {
                table.row($(this).closest('tr')).invalidate();
                $input = $(this).find('input[type="checkbox"]');
                if ($input) {
                    $input.prop("checked", !$input.prop("checked"));
                }
                if ($input.prop('checked')) {
                    $input.closest('tr').addClass('pregunta-seleccionada');
                    $(this).find('p.texto-seleccionada').html('<i class="fas fa-lg fa-fw fa-check text-green-darker" style="font-size:25px"></i>')
                } else {
                    $input.closest('tr').removeClass('pregunta-seleccionada');
                    $(this).find('p.texto-seleccionada').html('')
                }
            });

            $('tbody input', table.table().node()).each(function () {
                if ($(this).prop('checked')) {
                    $(this).closest('tr').addClass('pregunta-seleccionada');
                    $(this).closest('tr').find('p.texto-seleccionada').html('<i class="fas fa-lg fa-fw fa-check text-green-darker" style="font-size:25px"></i>');
                } else {
                    $(this).closest('tr').removeClass('pregunta-seleccionada');
                    $(this).closest('tr').find('p.texto-seleccionada').html('');
                }
            })
        });
    </script>
    <script src="{% static 'js/apps/examenes/enunciado-pregunta.js' %}"></script>

{% endblock js %}

examenes_app_principal/apps/front_examenes/templates/lista_examenes.html
{% extends "base_tablas.html" %}
{% load iso8601_datetime %}

{% block titulo_pagina %}
    Listado de examenes
{% endblock %}

{% block titulo %}
    Listado de examenes
{% endblock %}

{% block subtitulo %}
    Información de los examenes creados
{% endblock %}

{% block titulo_panel %}
    Listado de examenes
{% endblock %}

{% block contenido_panel %}
    <div class="table-responsive">
        <table class="data-combine table table-bordered">
            <thead>
                <tr>
                    <th>
                        Título
                    </th>
                    <th>
                        Grupo
                    </th>
                    <th>
                        Fecha de inicio
                    </th>
                    <th>
                        Fecha de fin
                    </th>
                    <th>
                        Iniciado
                    </th>
                    <th>
                        Terminado
                    </th>
                    <th>
                        Opciones
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for examen in lista_examenes %}
                    <tr>
                        <td>
                            {{ examen.titulo }}
                        </td>
                        <td>
                            {{ examen.grupo.nombre }}
                        </td>
                        <td>
                            {{ examen.fecha_inicio|iso8601_datetime }}
                        </td>
                        <td>
                            {{ examen.fecha_fin|iso8601_datetime }}
                        </td>
                        <td>
                            {{ examen.iniciado|yesno:"Sí,No,No" }}
                        </td>
                        <td>
                            {{ examen.terminado|yesno:"Sí,No,No" }}
                        </td>
                        <td>
                            <a class="btn btn-sm btn-green" href="{% url 'examenes:detalle_examen' examen.id %}">Ver examen</a>
                            {% if examen.iniciado == False %}
                                <a class="btn btn-sm btn-default" href="{% url 'examenes:modificar_examen' examen.id %}">Modificar</a>
                                <a class="btn btn-sm btn-success" href="{% url 'examenes:iniciar_examen' examen.id %}">Iniciar</a>
                            {% elif examen.iniciado == True %}
                                <a class="btn btn-sm btn-info" href="{% url 'examenes:consultar_calificaciones_examen' examen.id %}">Ver calificaciones</a>
                            {% endif %}
                            {% if  examen.iniciado == True and examen.terminado == False %}
                                <a class="btn btn-sm btn-danger" href="{% url 'examenes:terminar_examen' examen.id %}">Terminar examen</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}