examenes_app_principal/apps/front_grupos/urls.py
from django.urls import path

from .views import *

app_name = 'grupos'
urlpatterns = [
    path('registrar', registrar_grupo, name='registrar_grupo'),
    path('modificar/<int:pk>', modificar_grupo, name='modificar_grupo'),
    path('listar', consultar_grupos, name='consultar_grupos'),
    path('listar-grupos-estudiante', consultar_grupos_estudiante, name='consultar_grupos_estudiante'),
]

examenes_app_principal/examenes_app_principal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from apps.front_usuarios.views import inicio

urlpatterns = [
  path('usuarios/', include('apps.front_usuarios.urls')),
  path('grupos/', include('apps.front_grupos.urls')),
  path('examenes/', include('apps.front_examenes.urls')),

                path('', inicio, name='inicio'),
  path('select2/', include('django_select2.urls')),
  path('summernote/', include('django_summernote.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

examenes_app_principal/apps/front_grupos/models.py
# Create your models here.

examenes_app_principal/apps/front_grupos/forms.py
from django import forms

from django_microservices.models import MicroService
from django_select2.forms import Select2MultipleWidget


class GrupoForm(forms.Form):
    nombre = forms.CharField(max_length=250, label="Nombre del grupo")
    codigo = forms.CharField(max_length=150, label="Código del grupo (opcional)", required=False)
    numero = forms.CharField(max_length=50, label="Número del grupo (opcional)", required=False)
    estudiantes = forms.MultipleChoiceField(label="Estudiantes", widget=Select2MultipleWidget(), required=False)

    def __init__(self, *args, **kwargs):
        profesor = kwargs.pop('profesor', {})
        super(GrupoForm, self).__init__(*args, **kwargs)

        try:
            microservicio = MicroService.objects.get(name="api")
            respuesta = microservicio.remote_call(
                    "GET", api='api/usuarios/', headers={'MICROSERVICE-USER-PK': str(profesor['id'])}
            )

            if respuesta.status_code == 200:
                estudiantes = []
                for estudiante in respuesta.json():
                    if estudiante['rol'] == "Estudiante":
                        estudiantes.append((estudiante['id'], "%s %s" % (estudiante['first_name'], estudiante['last_name'])))
            else:
                estudiantes = []
        except Exception as e:
            estudiantes = []

        self.fields['estudiantes'].choices = estudiantes

examenes_app_principal/apps/front_grupos/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django_microservices.utilities import get_microservice_user_pk, get_microservice_user
from django_microservices.utilities import login_required
from rest_framework import status

from examenes_app_principal.utilities import verificar_rol, add_form_errors
from .forms import *


@login_required
@verificar_rol(roles_permitidos=["Profesor"])
def registrar_grupo(request):
    microservicio = MicroService.objects.get(name="api")
    profesor = get_microservice_user(request)
    form = GrupoForm(profesor=profesor)

    if request.method == 'POST':
        form = GrupoForm(request.POST, profesor=profesor)
        if form.is_valid():
            try:
                data = form.cleaned_data
                data.update({'profesor': get_microservice_user_pk(request)})
                respuesta = microservicio.remote_call(
                        "POST", api='api/grupos/', data=data, request=request
                )
            except Exception as e:
                messages.error(request, 'Ha ocurrido un error al guardar la información, por favor vuelva a intentar.')
                return redirect('grupos:consultar_grupos')

            if respuesta.status_code == status.HTTP_201_CREATED:
                messages.success(request, "Grupo registrado correctamente")
                return redirect('grupos:consultar_grupos')
            elif respuesta.status_code == status.HTTP_400_BAD_REQUEST:
                errores = respuesta.json()
                form = GrupoForm(request.POST, profesor=profesor)
                add_form_errors(form, errores)
                messages.error(request, "Por favor revise los campos en rojo")
                return render(request, "gestionar_grupo.html", {'form': form})
            else:
                messages.error(request, "Ha ocurrido un error al guardar la información, por favor vuelva a intentar.")
                return render(request, "gestionar_grupo.html", {'form': form})
        else:
            messages.error(request, "Por favor revise los campos en rojo")
            return render(request, "gestionar_grupo.html", {'form': form})

    return render(request, "gestionar_grupo.html", {'form': form})


@login_required
@verificar_rol(roles_permitidos=["Profesor"])
def modificar_grupo(request, pk):
    microservicio = MicroService.objects.get(name="api")
    profesor = get_microservice_user(request)

    try:
        respuesta = microservicio.remote_call(
                "GET", api='api/grupos/%s' % pk, request=request
        )
    except Exception:
        messages.error(request, 'Ha ocurrido un error, por favor vuelva a intentar.')
        return redirect('inicio')

    if respuesta.status_code == 200:
        grupo = respuesta.json()
    else:
        messages.error(request, 'Error al obtener los datos del grupo')
        return redirect('grupos:consultar_grupos')

    form = GrupoForm(initial=grupo, profesor=profesor)

    if request.method == 'POST':
        form = GrupoForm(request.POST, initial=grupo, profesor=profesor)
        if form.is_valid():
            try:
                data = dict(request.POST)
                respuesta = microservicio.remote_call(
                        "POST", api='api/grupos/%s' % pk, data=data, request=request
                )
            except Exception as e:
                messages.error(request, 'Ha ocurrido un error al guardar la información, por favor vuelva a intentar.')
                return redirect('grupos:consultar_grupos')

            if respuesta.status_code == status.HTTP_200_OK:
                messages.success(request, "Grupo modificado correctamente")
                return redirect('grupos:consultar_grupos')
            elif respuesta.status_code == status.HTTP_400_BAD_REQUEST:
                errores = respuesta.json()
                add_form_errors(form, errores)
                messages.error(request, "Por favor revise los campos en rojo")
                return render(request, "gestionar_grupo.html", {'form': form})
        else:
            messages.error(request, "Por favor revise los campos en rojo")
            return render(request, "gestionar_grupo.html", {'form': form})
    return render(request, "gestionar_grupo.html", {'form': form})


@login_required
def consultar_grupos(request):
    datos = []
    microservicio = MicroService.objects.get(name="api")
    try:
        respuesta = microservicio.remote_call(
                "GET", api='api/grupos/', request=request
        )
    except Exception as e:
        messages.error(request, 'Ha ocurrido un error, por favor vuelva a intentar.')
        return redirect('inicio')

    if respuesta.status_code == 200:
        grupos = respuesta.json()
    else:
        messages.error(request, 'Ha ocurrido un error, por favor vuelva a intentar.')
        return redirect('inicio')
    return render(request, "lista_grupos.html", {'lista_grupos': grupos})


@login_required
def consultar_grupos_estudiante(request):
    microservicio = MicroService.objects.get(name="api")
    try:
        respuesta = microservicio.remote_call(
                "GET", api='api/grupos/', request=request
        )
    except Exception as e:
        messages.error(request, 'Ha ocurrido un error, por favor vuelva a intentar.')
        return redirect('inicio')

    if respuesta.status_code == 200:
        grupos = respuesta.json()
    else:
        messages.error(request, 'Ha ocurrido un error, por favor vuelva a intentar.')
        return redirect('inicio')
    return render(request, "lista_grupos_estudiante.html", {'lista_grupos': grupos})

examenes_app_principal/apps/front_grupos/templates/gestionar_grupo.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block titulo_pagina %}
    Gestión de grupo
{% endblock %}

{% block titulo %}
    Gestión de grupo
{% endblock %}

{% block subtitulo %}
    Creación y edición de grupos
{% endblock %}

{% block titulo_panel %}
    Gestión de grupo
{% endblock %}

{% block contenido_panel %}
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <form method="POST" enctype="multipart/form-data">{% csrf_token %}
                {% bootstrap_form form layout="vertical" %}
{#                <a class="btn btn-default pull-left" href="{% url 'grupos:consultar_grupos' %}">Volver</a>#}
                <button type="submit" class="btn btn-primary pull-right">Enviar</button>
            </form>
        </div>
    </div>
{% endblock %}

examenes_app_principal/apps/front_grupos/templates/lista_grupos.html
{% extends "base_tablas.html" %}

{% block titulo_pagina %}
    Listado de grupos
{% endblock %}

{% block titulo %}
    Listado de grupos
{% endblock %}

{% block subtitulo %}
    Información de los grupos dirigidos
{% endblock %}

{% block titulo_panel %}
    Listado de grupos
{% endblock %}

{% block contenido_panel %}
    <div class="table-responsive">

        <table class="data-combine table table-bordered">
            <thead>
                <tr>
                    <th>
                        Nombre
                    </th>
                    <th>
                        Código de acceso
                    </th>
                    <th>
                        Código de grupo
                    </th>
                    <th>
                        Número de grupo
                    </th>
                    <th>
                        Opciones
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for grupo in lista_grupos %}
                    <tr>
                        <td>
                            {{ grupo.nombre }}
                        </td>
                        <td>
                            {{ grupo.codigo_acceso }}
                        </td>
                        <td>
                            {{ grupo.codigo }}
                        </td>
                        <td>
                            {{ grupo.numero }}
                        </td>
                        <td>
                            <a class="btn btn-sm btn-default" href="{% url 'grupos:modificar_grupo' grupo.id %}">Modificar</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

examenes_app_principal/apps/front_grupos/templates/lista_grupos_estudiante.html
{% extends "base_tablas.html" %}

{% block titulo_pagina %}
    Listado de grupos
{% endblock %}

{% block titulo %}
    Listado de grupos
{% endblock %}

{% block subtitulo %}
    Información de los grupos dirigidos
{% endblock %}

{% block titulo_panel %}
    Listado de grupos
{% endblock %}

{% block botones_panel %}
    <a class="btn btn-sm btn-success m-0 p-3" href="#">Ingresar a un grupo</a>
{% endblock %}

{% block contenido_panel %}
    <div class="table-responsive">

        <table class="data-combine table table-bordered">
            <thead>
                <tr>
                    <th>
                        Nombre
                    </th>
                    <th>
                        Código de acceso
                    </th>
                    <th>
                        Código de grupo
                    </th>
                    <th>
                        Número de grupo
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for grupo in lista_grupos %}
                    <tr>
                        <td>
                            {{ grupo.nombre }}
                        </td>
                        <td>
                            {{ grupo.codigo_acceso }}
                        </td>
                        <td>
                            {{ grupo.codigo }}
                        </td>
                        <td>
                            {{ grupo.numero }}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}